#CRED READ

SELECT ID FROM students;
SELECT ID,NAME FROM STUDENTS;
SELECT * FROM STUDENTS WHERE GRADE='A';
 SELECT NAME,ID FROM STUDENTS WHERE GRADE='A';

# ALIAS
SELECT ID AS STUD_ID FROM students;

#CRED UPDATE
UPDATE students SET NAME='SHABEER' WHERE NAME='MUHSIN';
UPDATE students SET AGE=19  WHERE NAME='JOHN DOE';

#DELETE
delete FROM students WHERE ID=3;
DELETE FROM STUDENTS;

desc STUDENTS;  #FOR DESCRIBE THE TABLE


SELECT * FROM students;