#NOT EQUAL !=
SELECT TITLE,RELAESED_YEAR FROM BOOKS WHERE RELEASED_YEAR= 2016;
SELECT TITLE FROM BOOKS WHERE RELEASED_YEAR != 2016;

#NOT LIKE
SELECT TITLE FROM BOOKS WHERE TITLE LIKE 'A%';
SELECT TITLE FROM BOOKS WHERE TITLE NOT LIKE 'A%';
SELECT TITLE,PAGES FROM BOOKS WHERE PAGES NOT LIKE '--';

#GREATERTHAN >
SELECT TITLE,PAGES FROM BOOKS WHERE PAGES>300;
SELECT TITLE,PAGES FROM BOOKS WHERE PAGES>=300;
SELECT 'A' > 'B'; #

#LESSTHAN <
SELECT 'A'<'B';

#AND &&
SELECT TITLE ,AUTHOR_FNAME,RELEASED_YEAR FROM BOOKS
WHERE AUTHOR_FNAME='NEIL' AND RELEASED_YEAR=2001;

SELECT 5>7 AND 6>4;

#OR ||
select TITLE,AUTHOR_FNAME,RELEASED_YEAR FROM BOOKS 
WHERE AUTHOR_FNAME='NEIL' || RELEASED_YEAR >2001;

SELECT 5>7 || 6>4;

SELECT TITLE,AUTHOR_FNAME,RELEASED_YEAR FROM BOOKS 
WHERE RELEASED_YEAR BETWEEN 2011 AND 2020;

SELECT TITLE,AUTHOR_FNAME,RELEASED_YEAR FROM BOOKS 
WHERE RELEASED_YEAR NOT BETWEEN 2011 AND 2020;

#IN/OUT
SELECT TITLE,RELEASED_YEAR FROM BOOKS WHERE RELEASED_YEAR IN(2010,2001,2016);
SELECT TITLE,RELEASED_YEAR FROM BOOKS WHERE RELEASED_YEAR NOT IN(2010,2001,2016);

#CASE
SELECT TITLE,RELEASED_YEAR,
   CASE
      WHEN RELEASED_YEAR >= 2001 THEN 'NEW BBOK'
	  ELSE 'OLD BOOK'
   END
FROM BOOKS;

SELECT TITLE,STOCK_QUANTITY,
   CASE
      WHEN STOCK_QUANTITY BETWEEN 0 AND 50 THEN '+'
      WHEN STOCK_QUANTITY BETWEEN 51 AND 100 THEN '++'
	  ELSE '+++'
   END
FROM BOOKS;

SELECT * FROM BOOKS;

