#distinct( showing names without duplicate)
select distinct grade from students;

#ORDER BY(ALPHABETIC OR NUM)
SELECT NAME  FROM students ORDER BY NAME;
SELECT NAME FROM students ORDER BY NAME DESC;

SELECT ID,NAME, age FROM students order by 1; #SHOW USING THE ID
SELECT NAME, age FROM students order by AGE DESC;

#LIMIT (TO OR FROM TO)
select NAME from students LIMIT 4;
SELECT NAME,AGE FROM students ORDER BY NAME LIMIT 3;
SELECT ID, NAME , AGE FROM students ORDER BY NAME LIMIT 2,6; #FROM 2 TO END

#LIKE(% FOR LONG WORDFOR _ SING LETTER)
SELECT NAME,AGE FROM students WHERE NAME LIKE '%SIN';
SELECT NAME ,AGE FROM students WHERE NAME LIKE 'JINA_';

SELECT concat(NAME,'-',AGE) AS NAMES FROM students 
ORDER BY AGE DESC LIMIT 3;

SELECT DESIGINATION, LOCATION FROM JOBS ORDER BY DESIGINATION, LOCATION;

SELECT * FROM students;