#CONCAT (COMBINE TWO COLUMS)
SELECT CONCAT (NAME ,' ', GRADE) FROM students; 
#COMBINED NAME AND GRADE B/W SPACE

SELECT CONCAT (NAME ,' ', GRADE,'-',AGE) AS COM FROM students;
SELECT CONCAT (NAME ,' ', GRADE,AGE,ID) AS COMBINE FROM students;

#SUBSTRING
SELECT SUBSTRING(NAME,1,7) AS TITLE FROM students;

#REPLACE
SELECT replace('HELLO WORD','LLO','8999');
#REPLACE LLO AS 8999
select concat(SUBSTRING(NAME,1,7),'-',GRADE) AS COM FROM students;

SELECT REPLACE(NAME,'A','EE')AS TITLE FROM students;
#NAME WHICH INCLUDE A CHANGE AS EE

select concat(SUBSTRING(REPLACE(NAME,'A','E'),1,7),'-',GRADE) AS COM FROM students;

#REVERSE
SELECT reverse('HELLO');
select reverse(NAME) AS TITLE FROM students;

#CHAR LENGTH(SEE THE LENGTH OF NAME)
SELECT char_length('HELLO');
SELECT NAME ,char_length(NAME) AS LENGTH FROM STUDENTS;

# CHANGE TO UPPER AND LOWER CASE
SELECT lower('HI');
SELECT UPPER(name) FROM STUDENTS;

SELECT CONCAT('MY FAV PERSON ', UPPER(NAME)) FROM students;
SELECT * FROM students;

SELECT NAME AS FORWARD, REVERSE(NAME) AS BACKEARD FROM students;